Repository Hanry3/projects, pull requests merged in 2024-10, with the labels that each got.

#34 Update readme.md in GO #hacktoberfest-accepted
  GO/readme.md
Labels: good first issue, hacktoberfest, hacktober, hacktoberfest-accepted

#31 Update readme.md Game/Sort the bubble clock!
  Game/Sort the bubble clock!/readme.md
Labels: hacktoberfest, hacktober, hacktoberfest-accepted

#30 Update readme.md Animated Login Form/2 directory #hacktoberfest
  Animated-Login-Form/2/readme.md
Labels: good first issue, hacktoberfest, hacktober, hacktoberfest-accepted

#36 Update style.css adding css for new function
  Card Hover Effect/style.css
Labels: enhancement, hacktoberfest, hacktober, hacktoberfest-accepted

#37 Update index.html adding term and conditon function
  Card Hover Effect/index.html
Labels: enhancement, hacktoberfest, hacktober, hacktoberfest-accepted

#28 Update readme.md in TODO App directory
  TODO App/readme.md
Labels: good first issue, hacktoberfest, hacktober, hacktoberfest-accepted

#39 Update Readme.md file
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktober, hacktoberfest-accepted

#51 Update readme.md in Animated Logibn form /2
  Animated-Login-Form/2/readme.md
Labels: documentation, good first issue

#52 Update readme.md in Animated Login Form/1
  Animated-Login-Form/1/readme.md
Labels: good first issue, hacktoberfest-accepted

#56 Add README files for Snake Game JS and Sort the Bubble Clock
  Game/README.md
Labels: documentation, good first issue, hacktoberfest, hacktober, hacktoberfest-accepted

#57 Update readme.md in Go directory
  GO/readme.md
Labels: documentation, good first issue, hacktoberfest, hacktober, hacktoberfest-accepted
